platform :ios, '8.0'

#Debug tools
def import_debug
    pod 'Reveal-iOS-SDK', :configurations => ['Debug']
    pod 'FLEX', :configurations => ['Debug']
end

target 'HiPDA' do
  use_frameworks!

  # Pods for HiPDA
  import_debug
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'SAMKeychain'
  pod 'MLeaksFinder'

  target 'HiPDATests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HiPDAUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
