platform :ios, '9.0'

#Debug tools
def import_debug
    pod 'Reveal-iOS-SDK', :configurations => ['Debug']
    pod 'FLEX', :configurations => ['Debug']
end

def import_JSONDecode
    pod 'Argo', '~> 4.1'
    pod 'Curry', '~> 3.0.0'
    pod 'Runes', '~> 4.0'
    pod 'HandyJSON', '~> 1.6'
end

def import_Rx
    pod 'RxSwift', '~> 3.0'
    pod 'RxCocoa', '~> 3.0'
    pod 'RxDataSources', '~> 1.0'
end

def import_Statistics
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'MLeaksFinder'
end

def import_Thoughtbot
    pod "Perform", :git => 'https://github.com/thoughtbot/Perform.git', :branch => 'swift-3'
    pod 'Delta', :git => "https://github.com/thoughtbot/Delta.git"
end

def import_SyntacticSugar
    pod 'Then', '~> 2.1.0'
end

target 'HiPDA' do
  use_frameworks!

  # Pods for HiPDA
  import_debug
  import_JSONDecode
  import_Rx
  import_Statistics
  import_Thoughtbot
  import_SyntacticSugar
  
  pod 'SAMKeychain'
  pod 'YYKeyboardManager'
  pod 'Moya/RxSwift', '~> 8.0.2'
  pod 'MBProgressHUD'
  pod 'SDWebImage', '~> 4.0.0'
  pod 'YYCache', '~> 1.0.4'
  pod 'MJRefresh', '~> 3.1.12'
  pod 'UITableView+FDTemplateLayoutCell', '~> 1.5.beta'
  pod 'WebViewJavascriptBridge', '~> 6.0.2'
    
  target 'HiPDATests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HiPDAUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# For Xcode 8.0 & Swift 3.0
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
            config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.10'
        end
    end
end
