platform :ios, '9.0'

#Debug tools
def import_debug
    pod 'Reveal-iOS-SDK', :configurations => ['Debug']
    pod 'FLEX', :configurations => ['Debug']
end

def import_JSONDecode
    pod 'Argo', :git => 'https://github.com/thoughtbot/Argo.git', :branch => 'master'
    pod 'Curry', :git => 'https://github.com/thoughtbot/Curry.git', :branch => 'master'
    pod 'Runes', :git => 'https://github.com/thoughtbot/Runes.git', :branch => 'master'
    pod 'HandyJSON', :git => 'https://github.com/alibaba/HandyJSON.git', :branch => 'master'
end

def import_Rx
    pod 'RxSwift', '~> 3.0.0-beta.1'
    pod 'RxCocoa', '~> 3.0.0-beta.1'
    pod 'RxDataSources', '~> 1.0.0-beta.2'
end

def import_Statistics
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'MLeaksFinder'
end

def import_Thoughtbot
    pod "Perform", :git => 'https://github.com/thoughtbot/Perform.git', :branch => 'swift-3'
    pod 'Delta', :git => "https://github.com/thoughtbot/Delta.git"
end

target 'HiPDA' do
  use_frameworks!

  # Pods for HiPDA
  import_debug
  import_JSONDecode
  import_Rx
  import_Statistics
  import_Thoughtbot
  
  pod 'SAMKeychain'
  pod 'YYKeyboardManager'
  pod 'Moya/RxSwift', :git => 'https://github.com/Moya/Moya', :branch => 'swift-3.0'
    
  target 'HiPDATests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HiPDAUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# For Xcode 8.0 & Swift 3.0
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
            config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.10'
        end
    end
end
