platform :ios, '8.0'

#Debug tools
def import_debug
    pod 'Reveal-iOS-SDK', :configurations => ['Debug']
    pod 'FLEX', :configurations => ['Debug']
end

target 'Hi!PDA' do
  use_frameworks!

  import_debug
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Moya'
  pod 'Moya/RxSwift'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'SSKeychain'

  target 'Hi!PDATests' do
    inherit! :search_paths
  end

  target 'Hi!PDAUITests' do
    inherit! :search_paths
  end

end
